### ISSUE TITLE
Cursor jump to last line of the file when save

### ISSUE THREAD

**Issue by kkpoon** [Krzysztof-Cieslak/vscode-elm#176] opened 2017-11-30 01:32 UTC
vscode 1.18.1
elm extension 0.15.1

when save the elm file, the cursor jump to the end of the file.

**Comment by Stijnkool** [comment] 2017-12-03 13:31
Although multiple plugins experience this issue, it won't be fixed within vscode.
It's up to the plugin authors to fix it. A high level solution is supplied in the reported issue. https://github.com/Microsoft/vscode/issues/38728

**Comment by Krzysztof-Cieslak** [comment] 2017-12-08 12:46
Duplicate of #174

**Closed by Krzysztof-Cieslak** 2017-12-08 12:46 UTC

**Comment by Stijnkool** [comment] 2017-12-10 23:01
Why is this issue closed?
This is not a bug in vscode itself.
It is a bug in the plugin as explained in https://github.com/Microsoft/vscode/issues/38728.

**Comment by allansideas** [comment] 2017-12-14 10:37
This only happens with "editor.formatOnSave": true, when running via the "ctrl+shift+p" Format Document shortcut, it doesn't jump to the EOF.

**Comment by joshhornby** [comment] 2018-01-02 15:27
This should be reopened, as it's a bug in this library.

**Comment by joshhornby** [comment] 2018-01-02 16:02
Anyone have any ideas on this? According to this comment https://github.com/Microsoft/vscode/issues/38728#issuecomment-349280013 we might need to not replace the entire document but just the section that's changed. Does `elm-format` support this?
